"""audit_log: full per-cycle AI reasoning trail

Revision ID: 85ba43cbb82c
Revises: e6310f1ea599
Create Date: 2026-09-15 00:11:58.750286
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85ba43cbb82c'
down_revision: str | None = 'e6310f1ea599'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('portfolio_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trigger', sa.String(length=32), nullable=False),
    sa.Column('decision_id', sa.String(length=36), nullable=True),
    sa.Column('decision_type', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('order_intent', sa.Boolean(), nullable=False),
    sa.Column('order_placed', sa.Boolean(), nullable=False),
    sa.Column('block_reason', sa.Text(), nullable=True),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('decision', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decision.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_decision_id'), 'audit_log', ['decision_id'], unique=False)
    op.create_index(op.f('ix_audit_log_portfolio_id'), 'audit_log', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_audit_log_timestamp'), 'audit_log', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_log_timestamp'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_portfolio_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_decision_id'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
