"""supervisor_policy (quant mode B)

Revision ID: b4c5fc952b78
Revises: 85ba43cbb82c
Create Date: 2026-09-15 01:26:33.350192
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4c5fc952b78'
down_revision: str | None = '85ba43cbb82c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supervisor_policy',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('portfolio_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('regime', sa.String(length=32), nullable=False),
    sa.Column('trade_today', sa.Boolean(), nullable=False),
    sa.Column('risk_multiplier', sa.Float(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supervisor_policy_active'), 'supervisor_policy', ['active'], unique=False)
    op.create_index(op.f('ix_supervisor_policy_created_at'), 'supervisor_policy', ['created_at'], unique=False)
    op.create_index(op.f('ix_supervisor_policy_portfolio_id'), 'supervisor_policy', ['portfolio_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_supervisor_policy_portfolio_id'), table_name='supervisor_policy')
    op.drop_index(op.f('ix_supervisor_policy_created_at'), table_name='supervisor_policy')
    op.drop_index(op.f('ix_supervisor_policy_active'), table_name='supervisor_policy')
    op.drop_table('supervisor_policy')
    # ### end Alembic commands ###
