"""price_bar (yahoo historical bars)

Revision ID: d51807c7abda
Revises: b4c5fc952b78
Create Date: 2026-09-15 02:37:20.750188
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd51807c7abda'
down_revision: str | None = 'b4c5fc952b78'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_bar',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('interval', sa.String(length=8), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'interval', 'ts', name='uq_price_bar_symbol_interval_ts')
    )
    op.create_index(op.f('ix_price_bar_interval'), 'price_bar', ['interval'], unique=False)
    op.create_index(op.f('ix_price_bar_symbol'), 'price_bar', ['symbol'], unique=False)
    op.create_index(op.f('ix_price_bar_ts'), 'price_bar', ['ts'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_price_bar_ts'), table_name='price_bar')
    op.drop_index(op.f('ix_price_bar_symbol'), table_name='price_bar')
    op.drop_index(op.f('ix_price_bar_interval'), table_name='price_bar')
    op.drop_table('price_bar')
    # ### end Alembic commands ###
