"""core schema: portfolio, journal, memory, safety

Revision ID: f4984e79bfd5
Revises: 
Create Date: 2026-09-14 16:52:37.804367
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f4984e79bfd5'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('owner', sa.String(length=128), nullable=False),
    sa.Column('broker', sa.String(length=32), nullable=False),
    sa.Column('execution_mode', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('safety_event',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('decision_id', sa.String(length=36), nullable=True),
    sa.Column('client_order_id', sa.String(length=64), nullable=True),
    sa.Column('allowed', sa.Boolean(), nullable=False),
    sa.Column('violation', sa.String(length=48), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_safety_event_created_at'), 'safety_event', ['created_at'], unique=False)
    op.create_table('system_event',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=48), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_event_created_at'), 'system_event', ['created_at'], unique=False)
    op.create_index(op.f('ix_system_event_event_type'), 'system_event', ['event_type'], unique=False)
    op.create_table('system_flag',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('decision',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('portfolio_id', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decision_type', sa.String(length=16), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=True),
    sa.Column('instrument_type', sa.String(length=16), nullable=True),
    sa.Column('action', sa.String(length=8), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('thesis', sa.Text(), nullable=True),
    sa.Column('entry_plan', sa.JSON(), nullable=True),
    sa.Column('exit_plan', sa.JSON(), nullable=True),
    sa.Column('invalidation_condition', sa.Text(), nullable=True),
    sa.Column('expected_outcome', sa.Text(), nullable=True),
    sa.Column('expected_holding_period', sa.String(length=64), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('reasoning_summary', sa.Text(), nullable=False),
    sa.Column('opportunities_considered', sa.JSON(), nullable=False),
    sa.Column('selected_opportunity', sa.String(length=32), nullable=True),
    sa.Column('rejected_opportunities', sa.JSON(), nullable=False),
    sa.Column('alternatives_considered', sa.JSON(), nullable=False),
    sa.Column('portfolio_state_snapshot', sa.JSON(), nullable=False),
    sa.Column('market_state_snapshot', sa.JSON(), nullable=False),
    sa.Column('claude_session_id', sa.String(length=64), nullable=True),
    sa.Column('memory_version', sa.String(length=16), nullable=True),
    sa.Column('portfolio_state_version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_decision_type'), 'decision', ['decision_type'], unique=False)
    op.create_index(op.f('ix_decision_portfolio_id'), 'decision', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_decision_timestamp'), 'decision', ['timestamp'], unique=False)
    op.create_table('memory',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('portfolio_id', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=16), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('current_revision', sa.Integer(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_category'), 'memory', ['category'], unique=False)
    op.create_index(op.f('ix_memory_key'), 'memory', ['key'], unique=False)
    op.create_index(op.f('ix_memory_portfolio_id'), 'memory', ['portfolio_id'], unique=False)
    op.create_table('portfolio_snapshot',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('portfolio_id', sa.String(length=64), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('state_version', sa.Integer(), nullable=False),
    sa.Column('portfolio_value', sa.Float(), nullable=False),
    sa.Column('cash', sa.Float(), nullable=False),
    sa.Column('buying_power', sa.Float(), nullable=False),
    sa.Column('gross_exposure', sa.Float(), nullable=False),
    sa.Column('net_exposure', sa.Float(), nullable=False),
    sa.Column('long_exposure', sa.Float(), nullable=False),
    sa.Column('short_exposure', sa.Float(), nullable=False),
    sa.Column('sector_exposure', sa.JSON(), nullable=False),
    sa.Column('asset_exposure', sa.JSON(), nullable=False),
    sa.Column('portfolio_volatility', sa.Float(), nullable=True),
    sa.Column('drawdown', sa.Float(), nullable=True),
    sa.Column('open_positions', sa.Integer(), nullable=False),
    sa.Column('open_orders', sa.Integer(), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_snapshot_as_of'), 'portfolio_snapshot', ['as_of'], unique=False)
    op.create_index(op.f('ix_portfolio_snapshot_portfolio_id'), 'portfolio_snapshot', ['portfolio_id'], unique=False)
    op.create_table('position',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('portfolio_id', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('instrument_type', sa.String(length=16), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('avg_price', sa.Float(), nullable=False),
    sa.Column('market_price', sa.Float(), nullable=True),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_position_portfolio_id'), 'position', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_position_symbol'), 'position', ['symbol'], unique=False)
    op.create_table('counterfactual',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('decision_id', sa.String(length=36), nullable=False),
    sa.Column('candidate_symbol', sa.String(length=32), nullable=False),
    sa.Column('candidate_action', sa.String(length=16), nullable=True),
    sa.Column('chosen', sa.Boolean(), nullable=False),
    sa.Column('decision_time_price', sa.Float(), nullable=True),
    sa.Column('future_prices', sa.JSON(), nullable=False),
    sa.Column('counterfactual_return', sa.Float(), nullable=True),
    sa.Column('counterfactual_drawdown', sa.Float(), nullable=True),
    sa.Column('reason_for_rejection', sa.Text(), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decision.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_counterfactual_decision_id'), 'counterfactual', ['decision_id'], unique=False)
    op.create_table('decision_candidate',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('decision_id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=True),
    sa.Column('chosen', sa.Boolean(), nullable=False),
    sa.Column('reason_for_rejection', sa.Text(), nullable=True),
    sa.Column('decision_time_price', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decision.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_candidate_decision_id'), 'decision_candidate', ['decision_id'], unique=False)
    op.create_table('memory_revision',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('memory_id', sa.String(length=36), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['memory_id'], ['memory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_revision_memory_id'), 'memory_revision', ['memory_id'], unique=False)
    op.create_table('order_record',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_order_id', sa.String(length=64), nullable=False),
    sa.Column('broker_order_id', sa.String(length=64), nullable=True),
    sa.Column('decision_id', sa.String(length=36), nullable=True),
    sa.Column('portfolio_id', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('instrument_type', sa.String(length=16), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('order_type', sa.String(length=24), nullable=False),
    sa.Column('limit_price', sa.Float(), nullable=True),
    sa.Column('stop_price', sa.Float(), nullable=True),
    sa.Column('time_in_force', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('filled_quantity', sa.Float(), nullable=False),
    sa.Column('avg_fill_price', sa.Float(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decision.id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_record_client_order_id'), 'order_record', ['client_order_id'], unique=True)
    op.create_index(op.f('ix_order_record_portfolio_id'), 'order_record', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_order_record_status'), 'order_record', ['status'], unique=False)
    op.create_index(op.f('ix_order_record_symbol'), 'order_record', ['symbol'], unique=False)
    op.create_table('trade',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('decision_id', sa.String(length=36), nullable=True),
    sa.Column('portfolio_id', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('instrument_type', sa.String(length=16), nullable=False),
    sa.Column('option_contract_id', sa.String(length=64), nullable=True),
    sa.Column('strategy_id', sa.String(length=64), nullable=True),
    sa.Column('strategy_version', sa.String(length=16), nullable=True),
    sa.Column('entry_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('exit_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('capital_allocated', sa.Float(), nullable=False),
    sa.Column('fees', sa.Float(), nullable=False),
    sa.Column('estimated_slippage', sa.Float(), nullable=True),
    sa.Column('realized_slippage', sa.Float(), nullable=True),
    sa.Column('gross_pnl', sa.Float(), nullable=True),
    sa.Column('net_pnl', sa.Float(), nullable=True),
    sa.Column('return_pct', sa.Float(), nullable=True),
    sa.Column('holding_period', sa.Float(), nullable=True),
    sa.Column('mfe', sa.Float(), nullable=True),
    sa.Column('mae', sa.Float(), nullable=True),
    sa.Column('market_regime', sa.String(length=32), nullable=True),
    sa.Column('volatility_regime', sa.String(length=32), nullable=True),
    sa.Column('thesis', sa.Text(), nullable=True),
    sa.Column('entry_reason', sa.Text(), nullable=True),
    sa.Column('exit_reason', sa.Text(), nullable=True),
    sa.Column('invalidation_condition', sa.Text(), nullable=True),
    sa.Column('claude_confidence', sa.Float(), nullable=True),
    sa.Column('decision_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('memory_version', sa.String(length=16), nullable=True),
    sa.Column('portfolio_state_version', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decision.id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_portfolio_id'), 'trade', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_trade_status'), 'trade', ['status'], unique=False)
    op.create_index(op.f('ix_trade_symbol'), 'trade', ['symbol'], unique=False)
    op.create_table('execution',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('fees', sa.Float(), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order_record.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_order_id'), 'execution', ['order_id'], unique=False)
    op.create_table('trade_event',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('trade_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['trade_id'], ['trade.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_event_trade_id'), 'trade_event', ['trade_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trade_event_trade_id'), table_name='trade_event')
    op.drop_table('trade_event')
    op.drop_index(op.f('ix_execution_order_id'), table_name='execution')
    op.drop_table('execution')
    op.drop_index(op.f('ix_trade_symbol'), table_name='trade')
    op.drop_index(op.f('ix_trade_status'), table_name='trade')
    op.drop_index(op.f('ix_trade_portfolio_id'), table_name='trade')
    op.drop_table('trade')
    op.drop_index(op.f('ix_order_record_symbol'), table_name='order_record')
    op.drop_index(op.f('ix_order_record_status'), table_name='order_record')
    op.drop_index(op.f('ix_order_record_portfolio_id'), table_name='order_record')
    op.drop_index(op.f('ix_order_record_client_order_id'), table_name='order_record')
    op.drop_table('order_record')
    op.drop_index(op.f('ix_memory_revision_memory_id'), table_name='memory_revision')
    op.drop_table('memory_revision')
    op.drop_index(op.f('ix_decision_candidate_decision_id'), table_name='decision_candidate')
    op.drop_table('decision_candidate')
    op.drop_index(op.f('ix_counterfactual_decision_id'), table_name='counterfactual')
    op.drop_table('counterfactual')
    op.drop_index(op.f('ix_position_symbol'), table_name='position')
    op.drop_index(op.f('ix_position_portfolio_id'), table_name='position')
    op.drop_table('position')
    op.drop_index(op.f('ix_portfolio_snapshot_portfolio_id'), table_name='portfolio_snapshot')
    op.drop_index(op.f('ix_portfolio_snapshot_as_of'), table_name='portfolio_snapshot')
    op.drop_table('portfolio_snapshot')
    op.drop_index(op.f('ix_memory_portfolio_id'), table_name='memory')
    op.drop_index(op.f('ix_memory_key'), table_name='memory')
    op.drop_index(op.f('ix_memory_category'), table_name='memory')
    op.drop_table('memory')
    op.drop_index(op.f('ix_decision_timestamp'), table_name='decision')
    op.drop_index(op.f('ix_decision_portfolio_id'), table_name='decision')
    op.drop_index(op.f('ix_decision_decision_type'), table_name='decision')
    op.drop_table('decision')
    op.drop_table('system_flag')
    op.drop_index(op.f('ix_system_event_event_type'), table_name='system_event')
    op.drop_index(op.f('ix_system_event_created_at'), table_name='system_event')
    op.drop_table('system_event')
    op.drop_index(op.f('ix_safety_event_created_at'), table_name='safety_event')
    op.drop_table('safety_event')
    op.drop_table('portfolio')
    # ### end Alembic commands ###
